version: "3.8"

services:
  api:
    build: .
    container_name: bookstore_api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bookstore
      - DB_PORT=5432
      - JWT_SECRET=supersecretkey
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:15
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
